### ISSUE TITLE
Consensus on using TwsHelper module for bootstrap usage.

### ISSUE THREAD

**Issue by ALTAMASH80** [LM-Commons/LmcAdmin#8]
Hi,

  I wanted to know what you people think about using [TwsHelper](https://github.com/neilime/twbs-helper-module) for managing bootstrap dependency. Thanks!

**Comment by visto9259** [comment]
Are you asking what we think of TwsHelper or are you asking if it should be embedded into LmcAdmin?

I have not looked at TwsHelper (I did not know it existed).  Most of my view rendering is done using React which renders Bootstrap html so it will not be of use to me.

As for as embedding TwsHelper into LmcAdmin, I would not recommend it.  View rendering should be the developer's choice and should not be forced to use a specific CSS such as Bootstrap. Views in a package should be minimalists since, most of the time, they will be overwritten by developers to comply with the application's overall UI design.  Tying the module to a specific UI would limit acceptance and adoption by the developer community.

For example, LmcUser provides a few basic views for user login, registration, etc. in `.phtml` files.  I overrode them with my own views but kept the overall logic of LmcUser.

**Comment by ALTAMASH80** [comment]
Thanks for the answer. I was asking for embedding it. Agree with your point that it should be the development team's choice.
